CREATE TABLE Device (
    Id NVARCHAR(100) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    IsEnabled BIT NOT NULL
);

CREATE TABLE Embedded (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  IpAddress NVARCHAR(100) NOT NULL,
  NetworkName NVARCHAR(100) NOT NULL,
  DeviceId NVARCHAR(100) NOT NULL,
  CONSTRAINT FK_Embedded_Device FOREIGN KEY (DeviceId) REFERENCES Device(Id) ON DELETE CASCADE
);

CREATE TABLE PersonalComputer (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  OperationSystem NVARCHAR(100) NOT NULL,
  DeviceId NVARCHAR(100) NOT NULL,
  CONSTRAINT FK_PersonalComputer_Device FOREIGN KEY (DeviceId) REFERENCES Device(Id) ON DELETE CASCADE
);

CREATE TABLE Smartwatch (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    BatteryPercentage NVARCHAR(10) NOT NULL,
    DeviceId NVARCHAR(100) NOT NULL,
    CONSTRAINT FK_Smartwatch_Device FOREIGN KEY (DeviceId) REFERENCES Device(Id) ON DELETE CASCADE
);